tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT 
  
  - name: react-js
    command: |
      cd frontend-react-js
      npm i

  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev     
  
  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt

  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      cd backend-flask

  #- name: sharp and clients3
  #  command: |
  #    cd aws/lambda/process-images
  #    npm i sharp
  #    npm i @aws-sdk/client-s3

  #- name: install serverless 
  #  command: |
  #    cd backend-flask/bin
  #    ./serverless/build


  - name: cdk
    before: |
      cd thumbing-serverlsess-cdk 
      cp .env.example .env
      npm i
      npm install aws-cdk -g
      npm i dotenv
  

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
