AWSTemplateFormatVersion: 2010-09-09

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: cruddurVPC
  
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CruddurIGW

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: cruddurRT

  RouteToIGW:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW
    Properties:      
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTable
  
  #RouteToLocal:
  #  Type: AWS::EC2::Route
  #  DependsOn: AttachIGW
  #  Properties:      
  #    RouteTableId: !Ref RouteTable
  #    DestinationCidrBlock: 10.0.0.0/16
  #    GatewayId: "local"

  PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: 
      CidrBlock: 10.0.0.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: CruddurSubnetPubA
      VpcId: !Ref VPC
  
  PubSubnetB:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: 
      CidrBlock: 10.0.4.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: CruddurSubnetPubA
      VpcId: !Ref VPC

  PubSubnetC:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: 
      CidrBlock: 10.0.8.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: CruddurSubnetPubc
      VpcId: !Ref VPC

  PriSubnetA:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.16.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: CruddurSubnetPriA
      VpcId: !Ref VPC


  PriSubnetB:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.20.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: CruddurSubnetPriB
      VpcId: !Ref VPC

  PriSubnetC:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: us-east-1c
      CidrBlock: 10.0.24.0/22
      EnableDns64: false
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: CruddurSubnetPriC
      VpcId: !Ref VPC

  SubnetPub1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubnetA
      RouteTableId: !Ref RouteTable

  SubnetPub2RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubnetB
      RouteTableId: !Ref RouteTable
  
  SubnetPub3RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubnetC
      RouteTableId: !Ref RouteTable

  SubnetPub1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSubnetA
      RouteTableId: !Ref RouteTable

  SubnetPub1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSubnetB
      RouteTableId: !Ref RouteTable

  SubnetPub1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PriSubnetC
      RouteTableId: !Ref RouteTable



